### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ApolloTang** [ApolloTang/react-native-redux-study#1]
- [ ] Need solution: break navigation reducer into smaller domain specific pieces.
- [ ] Research into setting up production environment
- [ ] Set up style guide (only accessible when ENV=development)
- [ ] Build a users list to test out Redux Async Action
- [ ] Research how to do Authentication
